## Trainee : AbdalRhman Gameel Ahmed Hebishy (G5)

In [1]:
import numpy as np

## Find the determinant of the matrix M1 :(By Code) :

In [2]:
M1 = np.array([[17, -11], [6, -3]])
det_M = np.linalg.det(M1)
print("Determinant of M:", det_M)

Determinant of M: 14.999999999999993


## Find the determinant of the matrix M2:(By Code) :

In [3]:
M2 = np.array([[1, 1, 2], [2, 3, 1], [3, 4, -5]])
det_M = np.linalg.det(M2)
print("Determinant of M:", det_M)

Determinant of M: -7.999999999999998


## Find the inverse matrix A-1 to the matrix A : (By Code)

In [4]:
A = np.array([[-3, -2], [3, 3]])
A_inv = np.linalg.inv(A)
print("Inverse of A:\n",A_inv)


Inverse of A:
 [[-1.         -0.66666667]
 [ 1.          1.        ]]


## Find the inverse matrix A-1 to the matrix A ([[0,1,1],[1,0,1],[1,1,1]]) : (By Code) :

In [5]:
import numpy as np


A = np.array([[1, 0, 1], [0, 1, 1], [1, 1, 1]])
A_inv = np.linalg.inv(A)
print("Inverse of A:\n",A_inv)

Inverse of A:
 [[ 0. -1.  1.]
 [-1.  0.  1.]
 [ 1.  1. -1.]]


In [6]:
A = np.array([
    [1, 4, 3, -1],
    [1, -1, 1, 2],
    [4, 1, 6, 5]
])

b = np.array([5, 6, 9])

try:
    solution = np.linalg.solve(A, b)
    print("Solution of the system:")
    print(solution)
except np.linalg.LinAlgError as e:
    print("The system has no solution.")



The system has no solution.


In [7]:
A = np.array([
    [1, -2, 1, -1],
    [2, -4, 1, 1],
    [1, -2, -2, 3]
])


b = np.array([3, 2, 1])

try:
    solution = np.linalg.solve(A, b)
    print("Solution of the system:")
    print(solution)
except np.linalg.LinAlgError as e:
    print("The system has no unique solution.")

    

The system has no unique solution.


In [8]:
# Create a 3x3 array
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("3x3 Array:")
print(arr)

3x3 Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
# Check the shape of the array
shape = arr.shape
print("Shape of the array:", shape)

Shape of the array: (3, 3)


In [10]:
# Select the first row
first_row = arr[0, :]
print("First row:")
print(first_row)

First row:
[1 2 3]


In [11]:
# Select the 2nd column
second_column = arr[:, 1]
print("2nd column:")
print(second_column)

2nd column:
[2 5 8]


In [12]:
# Select the 2nd element in the third column
second_element_third_column = arr[1, 2]
second_element_third_column

6

In [13]:
# Create a 2x2 array from the first two elements of the first 2 rows and columns
arr_2x2 = arr[:2, :2]
print("2x2 Array:")
print(arr_2x2)

2x2 Array:
[[1 2]
 [4 5]]


In [14]:
# Create a single row vector
row_vector = np.array([[10, 11, 12]])
print("Single row vector:")
print(row_vector)

Single row vector:
[[10 11 12]]


In [15]:
# Create a single column vector
column_vector = np.array([[13], [14], [15]])
print("Single column vector:")
print(column_vector)

Single column vector:
[[13]
 [14]
 [15]]
